trigger:
- master

strategy:
  matrix:
  
    MacOS Python36:
      imageName: 'macOS-latest'
      pyVersion: '3.6.x'
    MacOS Python37:
      imageName: 'macOS-latest'
      pyVersion: '3.7.x'
    MacOS Python38:
      imageName: 'macOS-latest'
      pyVersion: '3.8.x'
      
    Linux Python36:
      imageName: 'ubuntu-latest'
      pyVersion: '3.6.x'
    Linux Python37:
      imageName: 'ubuntu-latest'
      pyVersion: '3.7.x'
    Linux Python38:
      imageName: 'ubuntu-latest'
      pyVersion: '3.8.x'
      
    Windows Python36:
      imageName: 'windows-latest'
      pyVersion: '3.6.x'
    Windows Python37:
      imageName: 'windows-latest'
      pyVersion: '3.7.x'
    Windows Python38:
      imageName: 'windows-latest'
      pyVersion: '3.8.x'

pool:
  vmImage: $(imageName)
      
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pyVersion)'
  displayName: 'Use Python $(pyVersion)'

- script: |
    python -m pip install --upgrade pip
    pip install -r src/requirements.txt
  displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'pytest'
