name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  test:
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.x"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2

      - name: 🐍 Get Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: 🚚 Get Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: 🧪 Run Tests
        run: pytest