name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2

      - name: ✨ Setup .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"

      - name: 🛠️ Build Solution
        run: dotnet build ./website/builder/

      - name: 🌎 Build for Azure Static Site
        run: dotnet run --project './website/builder/' 'https://swharden.com/pyabf/'

      - name: 🚀 Deploy using FTP
        uses: SamKirkland/FTP-Deploy-Action@65c6a8f943bbf04faf9b59520a103318b418952e # 4.1.0
        with:
          local-dir: ./website/content/
          server-dir: /pyabf2/
          protocol: ftps
          server: swharden.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          log-level: minimal
          exclude: "[**/index.md]"
